# Generated by Django 2.2.3 on 2019-07-02 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20190701_2128'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='description',
            field=models.CharField(default='some', max_length=100),
            preserve_default=False,
        ),
    ]
